
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Daniel Bargmann", email = "daniel.bargmann@ipa.fraunhofer.de"},
]
dependencies = [
    "hvplot>=0.8.4",
    "streamz>=0.6.4",
    "altair>=5.0.1",
    "rospkg>=1.5.0",
]
requires-python = ">=3.8"
license = {text = "MIT"}
