[tool]
[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Daniel Bargmann", email = "daniel.bargmann@ipa.fraunhofer.de"},
]
dependencies = [
    "flet>=0.7.4",
    "bokeh>=3.1.1",
]
requires-python = ">=3.8"
license = {text = "MIT"}
